# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    body_converter:
        enabled: true
        validate: true # validation
        validation_errors_argument: violations # validation
    param_fetcher_listener: force
#    allowed_methods_listener:  true
#    routing_loader: true
    view:
        formats: { json: true, xml: false, rss: false }
        view_response_listener: true
    serializer:
        serialize_null: true # include null responses
#        view_response_listener:  true
#    exception:
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.
    format_listener:
        rules:
            - { path: ^/, fallback_format: json, priorities: [ json ] }
